-- =============================================
-- Migration 021: Atualizar Termo de Compromisso
-- Novo lema "Em busca da Excelência" + Diretriz 5
-- =============================================

UPDATE public.documento_templates
SET
  conteudo = '{"lema":"Em busca da Excelência","citacao":"A maior lição que os obreiros têm a aprender é a de sua própria insuficiência e a necessidade de se entregarem inteiramente a Deus. A religião de Cristo não consiste apenas no perdão dos pecados; significa a renovação do coração e a conformação da vida com a vontade de Deus. [...] A fidelidade nas pequenas coisas, o desempenho dos deveres comuns da vida, requerem esforço e determinação tanto quanto as maiores empresas.","citacao_ref":"Ellen G. White, Obreiros Evangélicos, pág. 273.","declaracao_intro":"diante de Deus e da liderança desta União, aceito o solene chamado para servir como missionário durante o quadriênio 2026-2029. Compreendo que o serviço ao Mestre exige esmero, minudência e uma busca constante pela excelência. Inspirado pelo compromisso de nunca me acomodar, assumo como meu lema pessoal: \"EU POSSO FAZER MELHOR\".","declaracao_corpo":"Pelo presente termo, comprometo-me voluntariamente a pautar meu ministério sob as seguintes diretrizes fundamentais:","diretrizes":["Evangelismo Relacional e Cuidado Atencioso: Dedicar-me-ei ao pastoreio individualizado, realizando o envio de mensagens semanais de instrução e encorajamento a todos os membros, interessados e aniversariantes da minha área de atuação, zelando para que cada alma se sinta assistida.","Edificação Coletiva pelo Curso Bíblico: Assumo o compromisso de realizar o Curso Bíblico com toda a igreja, integrando membros e interessados em um estudo profundo e sistemático da verdade presente, fortalecendo a unidade doutrinária.","Classe Bíblica Batismal Efetiva: Manterei a Classe Bíblica Batismal em funcionamento contínuo e ininterrupto, garantindo que seja um ambiente produtivo de preparo espiritual e doutrinário para os novos conversos.","Operosidade e Frutificação (Alvo Batismal): Empenhar-me-ei, sob a guia do Espírito Santo, para que o trabalho resulte em frutos visíveis para o Reino de Deus, realizando no mínimo um batismo por trimestre.","Acompanhamento de Relatórios Estatísticos: Dedicarei tempo para apreciar mensalmente os relatórios estatísticos de secretaria e minhas contas com Deus (MCCD)."],"declaracao_final":"Ao assinar este compromisso, declaro minha total submissão às diretrizes da União Norte Nordeste dos Adventistas do Sétimo Dia — Movimento de Reforma, reconhecendo que a fidelidade nos pequenos deveres é o que compõe a grande obra da eternidade."}',
  updated_at = now()
WHERE tipo = 'termo_compromisso';
